import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<Head>
				<meta
					content="width=device-width, height=100vh initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
					name="viewport"
				/>
			</Head>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
